# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it hasn't been touched
  in awhile. :sleepy: It will be closed in a week if no new activity is seen.

  Thanks for helping keep our house in order!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This pull request has been automatically closed because it has not been updated
  in the last 3 months. :sleepy: If you still need this change, please reopen it.

  Thanks for helping keep our house in order!
